a= input("Enter The First Number: ")
b= input("Enter The Second Number: ")
print("Addition of a and b is: ", int(a)+ int(b))
print("Substraction of a and b is: ", int(a)- int(b))
print("Multiplication of a and b is: ", int(a)* int(b))
print("Division of a and b is: ", int(a)/ int(b))
print("Modulas of a and b is: ", int(a)% int(b))
